"""
Author:     Sanjay Nainwal
GitHub:     https://github.com/nainwalsanju/Auto_job_applier_linkedIn
Description: Notification module for Telegram and other services.
"""

import requests
import os
from dotenv import load_dotenv
from modules.helpers import print_lg

# Load environment variables
load_dotenv()


def send_telegram_message(message: str) -> bool:
    """
    Sends a message via Telegram bot.
    Requires TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID in .env
    """
    token = os.getenv("TELEGRAM_BOT_TOKEN")
    chat_id = os.getenv("TELEGRAM_CHAT_ID")

    if not token or not chat_id:
        return False

    url = f"https://api.telegram.org/bot{token}/sendMessage"
    payload = {"chat_id": chat_id, "text": message, "parse_mode": "Markdown"}

    try:
        response = requests.post(url, json=payload, timeout=10)
        if response.status_code == 200:
            return True
        else:
            print_lg(f"⚠️ Telegram API Error: {response.text}")
            return False
    except Exception as e:
        print_lg(f"❌ Failed to send Telegram notification: {e}")
        return False


def notify_job_applied(
    job_title: str, company: str, recruiter_name: str = "None", ai_used: bool = False
):
    """Formats and sends a 'Job Applied' notification."""
    status_emoji = "🚀"
    ai_status = "✅ Yes" if ai_used else "❌ No"

    msg = (
        f"{status_emoji} *New Job Applied!*\n\n"
        f"*Title:* {job_title}\n"
        f"*Company:* {company}\n"
        f"*Recruiter:* {recruiter_name}\n"
        f"*AI Personalized:* {ai_status}\n\n"
        f"Generated by: [Auto Job Applier](https://github.com/nainwalsanju/Auto_job_applier_linkedIn)"
    )
    send_telegram_message(msg)


def notify_error(error_desc: str, context: str = ""):
    """Formats and sends an 'Error' notification."""
    msg = (
        f"⚠️ *Bot Alert: Error Detected*\n\n"
        f"*Context:* {context}\n"
        f"*Error:* {error_desc}\n"
    )
    send_telegram_message(msg)


def notify_session_summary(stats: dict):
    """Sends a session summary notification."""
    msg = (
        f"📊 *Session Complete Summary*\n\n"
        f"💼 *Jobs Processed:* {stats.get('jobs_processed', 0)}\n"
        f"✉️ *Messages Sent:* {stats.get('messages_sent', 0)}\n"
        f"🧠 *AI Requests:* {stats.get('ai_requests', 0)}\n"
    )
    send_telegram_message(msg)
