# LinkedIn Auto Job Applier - Exceptions Module
# Custom exception hierarchy for better error handling

from .custom_exceptions import (
    LinkedInApplierError,
    BrowserError,
    BrowserInitializationError,
    BrowserNavigationError,
    ElementNotFoundError,
    ElementInteractionError,
    SessionError,
    NotLoggedInError,
    SessionExpiredError,
    ApplicationError,
    ApplicationSubmissionError,
    QuestionAnsweringError,
    ResumeUploadError,
    AIError,
    AIConnectionError,
    AIResponseError,
    AIQuotaExceededError,
    ConfigurationError,
    MissingConfigurationError,
    InvalidConfigurationError,
    JobFilterError,
    BlacklistMatchError,
    JobParseError,
    RateLimitError,
    HumanVerificationError,
)

__all__ = [
    "LinkedInApplierError",
    "BrowserError",
    "BrowserInitializationError",
    "BrowserNavigationError",
    "ElementNotFoundError",
    "ElementInteractionError",
    "SessionError",
    "NotLoggedInError",
    "SessionExpiredError",
    "ApplicationError",
    "ApplicationSubmissionError",
    "QuestionAnsweringError",
    "ResumeUploadError",
    "AIError",
    "AIConnectionError",
    "AIResponseError",
    "AIQuotaExceededError",
    "ConfigurationError",
    "MissingConfigurationError",
    "InvalidConfigurationError",
    "JobFilterError",
    "BlacklistMatchError",
    "JobParseError",
    "RateLimitError",
    "HumanVerificationError",
]
